5 2 django allauth registration
thinknetica-django-lab-05/zhukovvlad pull request #54
Opened 2021-11-10 21:07 UTC by zhukovvlad

Closes #35

2021-11-11 10:16 UTC, morgangt requested changes
в requerments.txt не добавили зависимость django-allauth

2021-11-11 10:16 UTC, morgangt commented on main/views.py
>          return Seller.objects.get(user=self.request.user)
всю эту конструкцию надо заменить на get_or_create

2021-11-15 17:51 UTC, zhukovvlad commented on main/views.py
>          return Seller.objects.get(user=self.request.user)
Ок. Заменено.

2021-11-21 16:43 UTC, ilyuhi4 commented on main/utils/utils.py
> +        return str(sum([k * v for k, v in pairs]) % 11 % 10)
вот не ошибка, но очень режут глаз незначащие переменные

2021-11-21 16:43 UTC, ilyuhi4 commented on main/views.py
> +        seller = Seller.objects.get_or_create(user=self.request.user)[0]
тут ясно отчего этот метод используем?

2021-11-21 16:44 UTC, ilyuhi4 approved these changes

2021-11-21 20:00 UTC, zhukovvlad commented on main/utils/utils.py
> +        return str(sum([k * v for k, v in pairs]) % 11 % 10)
Так у питона же это одна из прелестей, что можно прям внутри списка цикл запустить. Классно же, нет?
А как правильно поступить?

2021-11-21 20:02 UTC, zhukovvlad commented on main/views.py
> +        seller = Seller.objects.get_or_create(user=self.request.user)[0]
Да. Юзеры и селлеры - сущности разные. Мы создаем юзера, но должны попасть на страницу апдейта селлера, поэтому если соответствующий селлер есть, то берем его, ежели нет, - то создаем нового.

2021-11-21 20:08 UTC, merged